### ISSUE TITLE
Request: use long polling

### ISSUE THREAD

**Issue by LegitTrevorTiernan** [kbrashears5/typescript-aws-sqs-helper#245]
Hi, I was just doing a test/experiment using this library. It looks like it's using short polling instead of long polling. In my case receiveAllMessagesAsync returned something like 119792 out of 120000 messages. It may be good to implement a long poll for a higher likelihood of getting all 120k.

**Comment by kbrashears5** [comment]
@LegitTrevorTiernan i just pushed a change that should do long polling now. defaults to 20 seconds, but you can override with
```javascript
waitTimeSeconds = 5
```
or whatever value you need

referenced [aws docs](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-short-and-long-polling.html) on how to implement long polling
